name: PDF

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    paths:
      - '.gitea/workflows/convert-to-pdf.yml'
      - 'README.md'

jobs:
  pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Read Git Info"
        id: "git_info"
        uses: YunaBraska/git-info-action@main

        # CONFIGS (Optional)
        with:
          workDir: '.'
          branch-fallback: 'main'
          tag-fallback: '0.0.1'
          tag-match-pattern: 'v1.*'
          fallback-commit-type: 'chore'
          fallback-commit-scope: 'performance'
          commit-msg-with-footer: 'true'
          max-changelog-length: 200

      - name: "Print Git Info to file"
        run: |
          sed -i "s,<div style=\"display:none;\">&raquo; Commit Sha: ##COMMIT_SHA%%</div>,\&raquo; Commit Sha: ${{ steps.git_info.outputs.tag_latest }},g" README.md
      - name: PDF Generation
        uses: leleobhz/markdown-to-pdf@main
        with:
          input_dir: ./
          output_dir: ./
          build_html: false
      - name: Rename PDF
        run: mv README.pdf leonardo_amaral_resume.pdf
      - name: Release
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: Curriculo em PDF
          path: leonardo_amaral_resume.pdf
