name: PDF

on:
  workflow_dispatch:
  push:
    branches:
      - resume
    paths:
      - '.gitea/workflows/convert-to-pdf.yml'
      - 'README.md'

jobs:
  pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set outputs
        id: git_info
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "Print Git Info to file"
        run: |
          sed -i "s,<div style=\"display:none;\">&raquo; Commit Sha: ##COMMIT_SHA%%</div>,\&raquo; Commit Sha: ${{ steps.git_info.outputs.sha_short }},g" README.md

      - name: Install markdown-pdf
        run: apt update && apt install -y pip hyphen-pt-br && pip install --break-system-packages rst2pdf[aafiguresupport,mathsupport,plantumlsupport,rawhtmlsupport,sphinx,svgsupport] xhtml2pdf pyphen

      - name: PDF Generation
        run: rst2pdf --raw-html --language=pt_BR -s a4,default -o leonardo_amaral_resume.pdf README.md

      - name: Release
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: Curriculo em PDF
          path: leonardo_amaral_resume.pdf
