name: PDF

on:
  workflow_dispatch:
  push:
    branches:
      - resume
    paths:
      - 'README.md'

jobs:
  pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PDF Generation
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./
          output_dir: ./
          build_html: false
      - name: Rename PDF
        run: mv README.pdf leonardo_amaral_resume.pdf
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: False
          title: "Curriculo em PDF"
          files: leonardo_amaral_resume.pdf

