name: PDF

on:
  workflow_dispatch:
  push:
    branches:
      - resume
    paths:
      - '.github/workflows/convert-to-pdf.yml'
      - 'README.md'

jobs:
  pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: Install markdown-pdf and tools
        run: apt update && apt install -y pandoc wget git && wget --content-disposition https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bookworm_$(dpkg --print-architecture).deb && dpkg -i wkhtmltox_0.12.6.1-3.bookworm_$(dpkg --print-architecture).deb || true && apt -f -y install

      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/actions/checkout/issues/1048#issuecomment-2772402071
      - name: Mark repository as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: "Print Git Info to file"
        run: |
          sed -i "s,##COMMIT_SHA%%,$(git rev-parse --short HEAD),g" README.md

      - name: HTML Generation
        run:  pandoc -f gfm -t html5 --css style.css -s README.md -o leonardo_amaral_resume.html

      - name: PDF Generation
        run:  pandoc -f gfm -t html5 --pdf-engine wkhtmltopdf --pdf-engine-opt '--disable-smart-shrinking' --pdf-engine-opt '--enable-external-links' --pdf-engine-opt '--margin-bottom' --pdf-engine-opt '15mm' --pdf-engine-opt '--margin-left' --pdf-engine-opt '15mm' --pdf-engine-opt '--margin-right' --pdf-engine-opt '15mm' --pdf-engine-opt '--margin-top' --pdf-engine-opt '15mm' --css style.css -s README.md -o leonardo_amaral_resume.pdf

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: False
          title: "Curriculo em PDF"
          files: leonardo_amaral_resume.pdf

